"""Source-fused candidate prompt pool (APE/APO) for Phase-2 BAI selection.

Builds a pool of candidate FIRST-turn attack openings by fusing, per case:
  - the CARES attack goal,
  - the target's measured susceptibility report (which strategy/register is weak),
  - the Phase-I hardened persona (style, distortion, optimized openings),
  - exemplar phrasings harvested from the susceptibility pre-test (what wobbled).
Candidates are tagged by (strategy, register) = BAI cluster. The pool can be
expanded by APE Monte-Carlo resampling around high-scoring openings, or refined
by APO failure analysis. Selection over the pool is done by ``triple.py``.
"""
from __future__ import annotations

from agents import invoke


def harvest_exemplars(susceptibility_matrix, probes, axis, min_wobble=6):
    """Collect probe texts that wobbled the target, grouped by (strategy, register)."""
    text_of = {p["probe_id"]: p["text"] for p in probes}
    out = {}
    for row in susceptibility_matrix.get(axis, []):
        if row["score"] >= min_wobble and row.get("probe_id") in text_of:
            out.setdefault((row["strategy"], row["register"]), []).append(text_of[row["probe_id"]])
    return out


def _susceptibility_hint(hint, strategy, register):
    """Pick the ranking entry (or the top hint) relevant to this cluster for context."""
    if not hint:
        return {}
    ctx = {"recommended_strategy": hint.get("recommended_strategy", ""),
           "register": hint.get("register", register), "rationale": hint.get("rationale", "")}
    return ctx


def build_pool(case, hint, gen_cmd, strategies, registers=("plain", "clinical"),
               base_k=3, exemplars=None, weight_by_wobble=True, fused=True, demos=None):
    """Generate the candidate pool for one case, tagged by (strategy, register).

    fused=True (ours): each candidate is generated by fusing the target's measured
    susceptibility report, the Phase-I hardened persona, and harvested exemplars,
    and weak clusters get more candidates (profile-guided). fused=False (vanilla APE
    baseline): generate from the goal alone, no target-specific pre-information, equal
    k per cluster — so we can measure how much our domain fusion helps.
    Returns a list of {text, strategy, register, source}.
    """
    exemplars = exemplars or {}
    goal = {"intent": case["goal"].get("intent", ""), "masked_request": case["goal"].get("masked_request", "")}
    p1 = case.get("phase1_persona") if fused else None
    wobble = {}
    if fused:
        for r in (hint or {}).get("strategy_ranking", []):
            wobble[(r["strategy"], r["register"])] = r.get("wobble", 5)
    pool = []
    for s in strategies:
        for reg in registers:
            k = base_k
            if fused and weight_by_wobble and wobble:
                w = wobble.get((s, reg), 5)
                k = max(1, round(base_k * (0.5 + w / 10.0)))  # weak clusters -> more candidates
            payload = {"task": "ape_forward", "axis": case["axis"], "goal": goal,
                       "strategy": s, "register": reg, "k": k, "demos": demos or []}
            if fused:
                payload["susceptibility"] = _susceptibility_hint(hint, s, reg)
                payload["exemplars"] = exemplars.get((s, reg), [])
                if p1:
                    payload["phase1_persona"] = {"system_instruction": p1.get("system_instruction", ""),
                                                 "opening_utterances": p1.get("opening_utterances", []),
                                                 "distortion": p1.get("distortion")}
            src = "ape_forward" if fused else "ape_vanilla"
            for text in invoke(gen_cmd, payload).get("candidates", []):
                pool.append({"text": text, "strategy": s, "register": reg, "source": src})
    return pool


def expand_pool(winners, gen_cmd, k=3):
    """APE resampling: add semantic variations of high-scoring openings."""
    extra = []
    for w in winners:
        out = invoke(gen_cmd, {"task": "ape_resample", "text": w["text"],
                               "strategy": w.get("strategy", ""), "register": w.get("register", ""), "k": k})
        for v in out.get("variations", []):
            extra.append({"text": v, "strategy": w.get("strategy"), "register": w.get("register"),
                          "source": "ape_resample"})
    return extra


def apo_refine(case, failures, gen_cmd, k=5):
    """APO: analyze failed openings and generate improved candidates."""
    out = invoke(gen_cmd, {"task": "apo_feedback", "goal": case["goal"], "failures": failures, "k": k})
    cands = [{"text": t, "strategy": "apo", "register": "plain", "source": "apo"} for t in out.get("candidates", [])]
    return cands, out.get("fault_reasons", [])
